remote_theme: just-the-docs/just-the-docs
title: Share Note
description: 
enable_copy_code_button: true
color_scheme: light
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  info:
    title: Info
    color: yellow
